FROM node:14.5 as builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
ENV PATH /usr/src/app/node_modules/.bin:$PATH
RUN npm install --silent
COPY . .
RUN npm run build

FROM nginx:latest 
# RUN rm -rf /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/
COPY nginx/lyrics-front /etc/nginx/sites-available/
RUN ln -s /etc/nginx/sites-available /etc/nginx/sites-enabled
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 9000
CMD ["nginx","-g","daemon off;"]